export interface IWeaponInfo {
  name: string;
  damage: number;
  range: number;
  rangeModifier: number;
  cycleTime: number;
  clipSize: number;
  bullets: number;
  gainRange?: number;
}

export const weaponInfos = [
  {
    name: "autoshotgun",
    range: 3000,
    rangeModifier: 0.7,
    damage: 23,
    cycleTime: 0.15,
    clipSize: 10,
    bullets: 11,
  },
  {
    name: "hunting_rifle",
    range: 8192,
    rangeModifier: 1,
    damage: 90,
    cycleTime: 0.25,
    clipSize: 15,
    bullets: 1,
  },
  {
    name: "pistol_magnum",
    range: 3500,
    rangeModifier: 0.75,
    damage: 80,
    cycleTime: 0.15,
    clipSize: 8,
    bullets: 1,
  },
  {
    name: "pistol",
    range: 2500,
    rangeModifier: 0.75,
    damage: 36,
    cycleTime: 0.15,
    clipSize: 15,
    bullets: 1,
  },
  {
    name: "dual_pistol",
    range: 2500,
    rangeModifier: 0.75,
    damage: 36,
    cycleTime: 0.075,
    clipSize: 30,
    bullets: 1,
  },
  {
    name: "pumpshotgun",
    range: 3000,
    rangeModifier: 0.7,
    damage: 25,
    cycleTime: 0.5,
    clipSize: 8,
    bullets: 10,
  },
  {
    name: "rifle_ak47",
    range: 3000,
    rangeModifier: 0.97,
    damage: 58,
    cycleTime: 0.13,
    clipSize: 40,
    bullets: 1,
    gainRange: 1500,
  },
  {
    name: "rifle_desert",
    range: 3000,
    rangeModifier: 0.97,
    damage: 44,
    cycleTime: 0.07,
    clipSize: 60,
    bullets: 1,
    gainRange: 1500,
  },
  {
    name: "rifle_sg552",
    range: 3000,
    rangeModifier: 0.97,
    damage: 33,
    cycleTime: 0.0825,
    clipSize: 50,
    bullets: 1,
    gainRange: 1500,
  },
  {
    name: "rifle",
    range: 3000,
    rangeModifier: 0.97,
    damage: 33,
    cycleTime: 0.0875,
    clipSize: 50,
    bullets: 1,
    gainRange: 1500,
  },
  {
    name: "shotgun_chrome",
    range: 3000,
    rangeModifier: 0.7,
    damage: 31,
    cycleTime: 0.5,
    clipSize: 8,
    bullets: 8,
  },
  {
    name: "shotgun_spas",
    range: 3000,
    rangeModifier: 0.7,
    damage: 28,
    cycleTime: 0.15,
    clipSize: 10,
    bullets: 9,
  },
  {
    name: "smg_mp5",
    range: 2500,
    rangeModifier: 0.84,
    damage: 24,
    cycleTime: 0.075,
    clipSize: 50,
    bullets: 1,
  },
  {
    name: "smg_silenced",
    range: 2200,
    rangeModifier: 0.84,
    damage: 25,
    cycleTime: 0.0625,
    clipSize: 50,
    bullets: 1,
    gainRange: 900,
  },
  {
    name: "smg",
    range: 2500,
    rangeModifier: 0.84,
    damage: 20,
    cycleTime: 0.0625,
    clipSize: 50,
    bullets: 1,
  },
  {
    name: "sniper_awp",
    range: 8192,
    rangeModifier: 1,
    damage: 115,
    cycleTime: 1.05,
    clipSize: 20,
    bullets: 1,
  },
  {
    name: "sniper_military",
    range: 8192,
    rangeModifier: 1,
    damage: 90,
    cycleTime: 0.25,
    clipSize: 30,
    bullets: 1,
  },
  {
    name: "sniper_scout",
    range: 8192,
    rangeModifier: 1,
    damage: 90,
    cycleTime: 0.9,
    clipSize: 15,
    bullets: 1,
  },
] as IWeaponInfo[];
